<a href="https://colab.research.google.com/github/lusekelok/diveintocode-ml/blob/master/Implementation%20of%20matrix%20product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Matrix product

import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [2]:
#[Problem 1] Matrix product is calculated manually

The product of two matrices can be computed by multiplying elements of the first row of the first matrix with the first column of the second matrix then, add all the product of elements. Continue this process until each row of the first matrix is multiplied with each column of the second matrix.

In [3]:
#[Problem 2] Calculation by NumPy function

#using matmul()
mat_product = np.matmul(a_ndarray, b_ndarray)
mat_product

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [4]:
#using dot()
mat_product1 = np.dot(a_ndarray, b_ndarray)
mat_product1

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [5]:
# using @
mat_product2 = a_ndarray @ b_ndarray
mat_product2

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [6]:
#[Problem 3] Implementation of calculation of a certain element & #[Problem 4] Creating a function that performs matrix multiplication

# Program to multiply two matrices using nested loops
  
# take a 3x3 matrix

def multi_matrix(A,B):
  result = np.array([[0, 0, 0, 0],[0, 0, 0, 0],[0, 0, 0, 0]])  
# iterating by row of A
  for i in range(len(A)):
  
    # iterating by coloum by B 
      for j in range(len(B[0])):
  
        # iterating by rows of B
          for k in range(len(B)):
              result[i][j] += A[i][k] * B[k][j]
  
  for r in result:
    print (r)

multi_matrix([[12,7,3],[4,5,6],[7,8,9]], [[5,8,1,2],[6,7,3,0],[4,5,9,1]])

[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


In [9]:
#[Problem 5] Judge the input whose calculation is not defined

def multi_matrix1(A,B):
  if len(A) == len(B[0]):
    result = np.array([[0, 0, 0, 0],[0, 0, 0, 0],[0, 0, 0, 0]])  
# iterating by row of A
    for i in range(len(A)):
  
    # iterating by coloum by B 
        for j in range(len(B[0])):
  
        # iterating by rows of B
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
  
    for r in result:
      print (r)
  else:
      print ("Not defined")

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])
multi_matrix1(d_ndarray, e_ndarray)

Not defined


In [10]:
#[Problem 6] Transposition
e_ndarrayT = np.transpose(e_ndarray)
print(e_ndarrayT)
multi_matrix1(d_ndarray, e_ndarrayT)

[[-9  6]
 [ 8 -5]
 [ 7  4]]
[46 -4  0  0]
[-34  73   0   0]
[0 0 0 0]
